services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: maindb
    command: -p 5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8000:8000
  services:
    container_name: lux_container
    image: lux_project
    build: .
