services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: maindb
    networks:
      - docker

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - docker

  lux_project:
    container_name: lux_project
    image: lux_project
    depends_on:
      - postgres
    build: .
    networks:
      - docker

networks:
  docker:
    external: false
    name: docker