services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: maindb
    networks:
      - docker

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    # ports:
    #   - 8080:8080
    networks:
      - docker

  backend:
    container_name: backend
    image: backend
    depends_on:
      - postgres
    build: ./scraper
    networks:
      - docker
  
  frontend:
    container_name: frontend
    image: frontend
    depends_on:
        - backend
        - postgres
    build: ./frontend
    networks:
      - docker
    ports:
      - 8080:8080 # switch to 8000 then uncomment adminer ports to run both adminer and web page (for debugging mainly)

networks:
  docker:
    external: false
    name: docker
