services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - docker

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - postgres
  #   # ports:
  #   #   - 8080:8080
  #   networks:
  #     - docker

  app:
    container_name: app
    image: app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    build: ./app
    networks:
      - docker

networks:
  docker:
    external: false
    name: docker
