services:
  postgres:
    build: .docker/postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  backend:
    build: .docker/backend
    depends_on:
      - postgres
  frontend:
    build: .docker/frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - postgres
  #   # ports:
  #   #   - "8080:8080"
  #   networks:
  #     - docker