services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgres/data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - postgres
  #   # ports:
  #   #   - "8080:8080"
  #   networks:
  #     - docker

  app:
    container_name: app
    image: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    build: ./app
